NAMA_LENGKAP = {
    "gilang": "Gilang Al-Raffi",
    "salwa": "Siti Salwa Azzahra",
    "cintany": "Maria Bernadina B. Cintany Lustin",
    "rafif": "Muhamad Rafif Al-Hafizh",
    "bufatia": "Fatia Amalia Maresti, S.Si., M.Si.",
    "aznur": "L.M.Aznur Syahfajar",
    "mylo": "Mylo Aleffa Rahman",
    "sabrina": "Sabrina Nur Anisah",
    "vito": "Muhammad Vito Aristawidya",
    "firna": "Firna Ulfiani R",
    "reefy": "Muhammad Reefy Hidayatullah",
    "aulia": "Aulia Rahmadiva Wardana",
    "maysa": "Maysa Zaidee Aulia",
    "caca": "Salsa Paringga Pangestu Ningsih",
    "nita": "Nita Sawalia Fitri",
    "thiodas": "Thiodas Heni Pakpahan",
    "aldi": "Aldi Daim Fauzan",
    "yusuf": "Yusuf",
    "raditio": "Raditio Ananto Hargiyanto",
    "oleen": "Paulina Bota Kolin",
    "panji": "Naufal Panji Purnomo",
}